import { array, number, object, string, TypeOf, date, mixed, boolean } from "yup";
var moment = require("moment");

export const userSchema = object({
  mobileNo: string().required().min(10),
  status: mixed().oneOf(["NEW", "APPROVED", "DECLINED", "MORE_INFO"]),

  name: string().required().min(3),
  email: string().optional(),
  fatherName: string().min(3),
  motherName: string().min(3),
  guardianName: string().optional().min(3),
  wifeName: string().optional().min(3),
  husbandName: string().optional().min(3),
  applications: string(),
  relationshipWithGuardian: string().optional(),
  address: object({
    line1: string().optional(),
    line2: string().optional(),
    line3: string().optional(),
    city: string().optional(),
    district: string().optional(),
    state: string().optional(),
    country: string().optional(),
    pinCode: string().optional(),
  }).default(undefined),
  aadharNo: string().optional(),
  panNo: string().optional(),
  voterId: string().optional(),
  disabledGovernmentId: string().optional(),
  rationCard: string().optional(),
  sex: string().optional(),
  education: string().optional(),
  bloodGroup: string().optional(),
  dob: string().optional(),
  disability: string().optional(),
  natureOfDisability: string().optional(),
  documents: string().optional(),
  jobApplication: object({
    status: string().optional(),
    applicationType: string().required(),
    date: string().required(),
    jobType: string().optional(),
    experience: boolean().optional(),
    trainingNeeded: boolean().optional(),
    trainingDetails: string().optional(),
    expectedSalary: string().optional(),
    nightShits: boolean().optional(),
    relocate: boolean().optional(),
    otherInfo: string().optional(),
    supportingDocuments: array().optional(),
  }).default(undefined),
});

export type User = TypeOf<typeof userSchema>;
